CREATE DATABASE IF NOT EXISTS `PERSOS` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
USE `PERSOS`;

CREATE TABLE `ANIMES` (
  `noma` VARCHAR(42),
  `saisons` VARCHAR(42),
  `année` VARCHAR(42),
  `nomp` VARCHAR(42),
  PRIMARY KEY (`noma`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `APPARTIENT_A` (
  `noma` VARCHAR(42),
  `nomg` VARCHAR(42),
  PRIMARY KEY (`noma`, `nomg`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `GENRE` (
  `nomg` VARCHAR(42),
  `thème` VARCHAR(42),
  `public_visé` VARCHAR(42),
  PRIMARY KEY (`nomg`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `STUDIO` (
  `noms` VARCHAR(42),
  `pdg` VARCHAR(42),
  `nationalité` VARCHAR(42),
  `noma` VARCHAR(42),
  `nomp` VARCHAR(42),
  PRIMARY KEY (`noms`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `AIME` (
  `nomf` VARCHAR(42),
  `nomp` VARCHAR(42),
  `nomg` VARCHAR(42),
  `noma` VARCHAR(42),
  PRIMARY KEY (`nomf`, `nomp`, `nomg`, `noma`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `PERSO` (
  `nomp` VARCHAR(42),
  `âge` VARCHAR(42),
  `sexe` VARCHAR(42),
  `origine` VARCHAR(42),
  PRIMARY KEY (`nomp`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

CREATE TABLE `FAN` (
  `nomf` VARCHAR(42),
  `prénomf` VARCHAR(42),
  `âge` VARCHAR(42),
  `sexe` VARCHAR(42),
  `nationalité` VARCHAR(42),
  PRIMARY KEY (`nomf`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

ALTER TABLE `ANIMES` ADD FOREIGN KEY (`nomp`) REFERENCES `PERSO` (`nomp`);
ALTER TABLE `APPARTIENT_A` ADD FOREIGN KEY (`nomg`) REFERENCES `GENRE` (`nomg`);
ALTER TABLE `APPARTIENT_A` ADD FOREIGN KEY (`noma`) REFERENCES `ANIMES` (`noma`);
ALTER TABLE `STUDIO` ADD FOREIGN KEY (`nomp`) REFERENCES `PERSO` (`nomp`);
ALTER TABLE `STUDIO` ADD FOREIGN KEY (`noma`) REFERENCES `ANIMES` (`noma`);
ALTER TABLE `AIME` ADD FOREIGN KEY (`noma`) REFERENCES `ANIMES` (`noma`);
ALTER TABLE `AIME` ADD FOREIGN KEY (`nomg`) REFERENCES `GENRE` (`nomg`);
ALTER TABLE `AIME` ADD FOREIGN KEY (`nomp`) REFERENCES `PERSO` (`nomp`);
ALTER TABLE `AIME` ADD FOREIGN KEY (`nomf`) REFERENCES `FAN` (`nomf`);