DROP TABLE IF EXISTS PRET;
DROP TABLE IF EXISTS LECTEUR;
DROP TABLE IF EXISTS LIVRE;

CREATE TABLE LIVRE (
        COTE    CHAR(6),
        TITRE    VARCHAR(255) NOT NULL,
        CATEGORIE    VARCHAR(30) NOT NULL,
        AUTEUR    VARCHAR(128),
	PRIMARY KEY (COTE)
);

CREATE TABLE LECTEUR(
    NOLECTEUR INT NOT NULL,
    NOM VARCHAR(128),
    ADRESSE VARCHAR(255),
    PRIMARY KEY(NOLECTEUR)
);

DROP TABLE IF EXISTS PRET;
CREATE TABLE PRET (
    COTE    CHAR(6),
    NOLECTEUR    INT,
    DATEEMPRUNT date NOT NULL,
    DATELIMITE date NOT NULL,
    RENDU CHAR(3) NOT NULL,
    PRIMARY KEY (COTE,NOLECTEUR),
    FOREIGN KEY (COTE) REFERENCES LIVRE(COTE),
    FOREIGN KEY (NOLECTEUR) REFERENCES LECTEUR(NOLECTEUR)
);



